### ISSUE TITLE
你好，我使用你的demo的时候并不能使用

### ISSUE THREAD

**Issue by underconverbg** [HelloSoul/AndroidWebrtcAec#2]
你好，我使用你的demo的时候并不能使用，没有录音到

**Comment by underconverbg** [comment]
第一次编译的时候报machine/cpu-features.h not fount 我把machine/cpu-features.h 的引入禁止以后并不能构建工程

**Comment by HelloSoul** [comment]
如果有时间的话把not found的错误信息贴一下

**Comment by underconverbg** [comment]
1.首先我第一次build这个项目出现如下错误
   - C:\Users\Administrator\AppData\Local\Android\Sdk\ndk-bundle\build\core\setup-app.mk
   Error:(81) Android NDK: Application targets deprecated ABI(s): armeabi mips    
   Error:(82) Android NDK: Support for these ABIs will be removed in a future NDK release. 

2.然后我修改libwebrtcaec/src/main/jni/Appliction.mk
   APP_ABI :=armeabi armeabi-v7a x86 mip 改为 APP_ABI := armeabi-v7a
   rebuild
  
3.然后产生如下报错:
Warning:warning: '__ARM_ARCH_7__' macro redefined [-Wmacro-redefined]
Error:fatal error: 'machine/cpu-features.h' file not found
Error:Execution failed for task ':libwebrtcaec:ndkBuild'.
> Process 'command 'C:\Users\Administrator\AppData\Local\Android\Sdk\ndk-bundle/ndk-build.cmd'' finished with non-zero exit value 2

4.然后全局搜索 machine/cpu-features
在libwebrtcaec\src\main\jni\external\webrtc\system_wrappers\source\android\cpu-features.c
下找到如下代码:
#include <sys/system_properties.h>
#ifdef __arm__
#define __ARM_ARCH_7__
#include <machine/cpu-features.h>
#endif
#include <pthread.h>
#include "cpu-features.h"
我屏蔽如下代码:
#ifdef __arm__
#define __ARM_ARCH_7__
#include <machine/cpu-features.h>
#endif
编译成功以后，成功安装到红米5plus以及小米4,但是在点击开始，听到测试音频并且说话

点击停止，点击回声消除效果播放，并没有任何响应
希望作者能帮帮我。谢谢
