### ISSUE TITLE
效果不行

### ISSUE THREAD

**Issue by LNeway** [HelloSoul/AndroidWebrtcAec#4]
目前使用Nexus 5测试了一下，但是效果感觉不行，回声消除后的结果基本上无法听清

**Comment by LNeway** [comment]
嗯，是的

**Comment by garethibabylabs** [comment]
我这里也没声音

**Comment by HelloSoul** [comment]
没有声音的情况可以看一下上个问题的回答
[https://github.com/HelloSoul/AndroidWebrtcAec/issues/2](url)

**Comment by wzw88486969** [comment]
<uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
没有声音的把这个加上就可以了
不然录制打不开，也不崩溃
